#pragma once
#include <vector>

using std::vector;

// DO NOT EDIT THIS FILE IN ANY WAY

// Node class for Linked List
class Ex3Node {
public:
	int data;
	Ex3Node* next;

	Ex3Node(int val) : data(val), next(nullptr) { ; };
	Ex3Node(int val, Ex3Node* nd) : data(val), next(nd) { ; };
};

class List
{
public:
	// Constructors and destructor
	List();
	~List();

	// Mutators
	// PARAM: val = value to be inserted
	// POST: inserts val at the front of the list
	void insert(int val);

	// PARAM: val = value to be removed from list
	// POST: removes all incidences of val from list,
	//       returns the number of values removed
	// To be completed for exercise 3
	int remove(int val);

	// Accessors
	bool check(const vector<int> & v) const;

	// Prints contents of list starting from head
	void print() const;

private:
	Ex3Node* head;

	// Helper method for destructor
	void deleteList();
};